### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by Yoda-Man** [jksevend/side_navigation#11]
Hi do you have examples for using the Theme options

SideNavigationBarTheme Fields
ItemTheme fields
TogglerTheme fields

**Comment by jksevend** [comment]
Hello @Yoda-Man 
No examples for using the themes do not exist currently. Since i thought they are pretty easy to use. I am at work right now. Will provide you with some examples later on in this issue

**Comment by WOWDeveloperX** [comment]
> Привет @Yoda-Man Никаких примеров использования темы в настоящее время не существует. Так как я думал, что они довольно просты в использовании. Сейчас я на работе. Я приведу вам несколько примеров позже в этом выпуске

я столько жду))
