### ISSUE TITLE
textStyle for label and icon size

### ISSUE THREAD

**Issue by Viper-Bit** [jksevend/side_navigation#12]
it's useful to change textStyle for each label and changing icon size maybe by theme.
if u accept PR i can make one.

**Comment by jksevend** [comment]
Hey @Viper-Bit 
I also think more style customizations should be implemented. You can create a PR and I will accept it if there are no further remarks 🙂

**Comment by WOWDeveloperX** [comment]
hello, is it possible to remove the icon and at least somehow change the text style?

**Comment by jksevend** [comment]
Hey @WOWDeveloperX 
making the icons optional should be no problem. Im currently working for a better solutions for styling where your feature will be implemented
