### ISSUE TITLE
Overflow error error when reducing size

### ISSUE THREAD

**Issue by bqMoonlight** [jksevend/side_navigation#13]
Hi, i found a bug that i think is quite easy to fix, when side bar is expanded try to pull right side of the window to shrink window width, at the moment when size of whole window is smaller then size of side bar, you will get overflow error. 
I think if the width of window is smaller then (lets say 600) then it should auto fold to prevent this error from happening

**Comment by jksevend** [comment]
Hello @bqMoonlight !
I am aware of this misbehaviour although I dit not come up with a fix yet. 
I tried wrapping everything and limiting its height and width but that did not seem to work.

My current plan however is to make us of the LayoutBuilder widget.

**Comment by bqMoonlight** [comment]
Hi, thank you for a reply.

I did something similar in my own playground,i also did not managed to solve this issue,what i did was listen to media query,and when screen width is less then 800 i would fold the side bar and problem is gone.
Or the max screen can be limited by platform code.

I would also like to ask,is there a way to change default animation of sidebar?
And i did not look what you used for sidebar item,but when you fold it animation is not smooth,icos just kinda suddenly disappear. I have smoother transition on my own example,and so does easy sidemenu. I think you can improve this part!
Other then those few things its very nice side menu
