### ISSUE TITLE
How to customise the size navigation bar.

### ISSUE THREAD

**Issue by BossPanyawut** [jksevend/side_navigation#18]

**Comment by jksevend** [comment]
Hello @BossPanyawut 
Currently the size of the navigation bar uses a width (both for expanded and not expanded state) which is hardcoded into the widget. My Future plans includes to not use a hardcoded width but rather use a ``LayoutBuilder`` instead. A plan for **customizing** the width of the side navigation bar by passing a width to its constructor is **not planned**
