### ISSUE TITLE
How to detect drawer button click

### ISSUE THREAD

**Issue by SapnaJainScaleupally** [jksevend/side_navigation#5]
Please let me know when i click on the bottom button that is use for open and close drawer 
is there any key to detect that drawer is open or not? 
i want to perform some action on drawer button click
![Screenshot (93)](https://user-images.githubusercontent.com/86678155/144400535-d5159a79-b192-476d-82fb-f2f58ab082e6.png)

**Comment by jksevend** [comment]
Hello @SapnaJainScaleupally .
Right now there is no way of obtaining an event like this. Since toggling the expanded state of the bar is not up to the user but rather to the framework in my opinion.

Maybe this will work out with the footer implementation in a future release

**Comment by jksevend** [comment]
Hello @SapnaJainScaleupally again!
So in the last few days I was able to make a functionality work where you can define a custom toggler widget with an optional onToggle method which gets called after the internal one (which sets the state, changes the width and animates). 
I think this would be a nice solution. 

Little preview is literally just:
`toggler: SideBarToggler(onToggle: () => print('I get printed out after the animation'),),`

**Comment by jksevend** [comment]
feature implemented with 0.0.7
